title: Tee Hwei Xin


![photo_2023-02-04_21-59-00](https://github.com/Hwei-Xin/Portfolio/assets/146412796/d9a29efb-9ad5-41e9-be05-600096f5c745)












#description: Aspiring Business Analyst
show_downloads: False
theme: jekyll-theme-minimal
