title: Tee Hwei Xin
Image: ![photo_2023-02-04_21-59-00](https://github.com/Hwei-Xin/Portfolio/assets/146412796/a6ac6283-cc6d-43d0-a9b3-6fd61a2550de)
#description: Aspiring Business Analyst
show_downloads: False
theme: jekyll-theme-minimal
